[package]
name = "proton_shared"
version = "0.1.0"
authors = ["kbrandt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.18.0"
strum_macros = "0.18.0"
lazy_static = "1.4.0"
parking_lot = "0.11.0"
